// Shared search UI utilities
// Used by both SearchBar (inline dropdown) and SearchModal (dialog)

import type { SearchResult } from "./search-engine";

// Render search results into a container
// Matches the visual design: subsection title + excerpt per row, fully clickable
export function renderResults(
  container: HTMLElement,
  results: SearchResult[],
  messageEl?: HTMLElement,
): void {
  container.innerHTML = "";

  if (messageEl) {
    if (results.length > 0) {
      messageEl.textContent = `${results.length} result${results.length === 1 ? "" : "s"}`;
      messageEl.hidden = false;
    } else {
      messageEl.hidden = true;
    }
  }

  for (const result of results) {
    const row = document.createElement("div");
    row.className = "search-result";

    const link = document.createElement("a");
    link.href = result.url;
    link.className = "search-result-link";

    const title = document.createElement("span");
    title.className = "search-result-title";
    title.textContent = result.title;

    const excerpt = document.createElement("span");
    excerpt.className = "search-result-excerpt";
    // Pagefind excerpts contain <mark> tags for match highlighting.
    // This content is generated by Pagefind at build time from our own indexed HTML —
    // it only contains text and <mark> wrappers, not arbitrary user input.
    excerpt.innerHTML = result.excerpt;

    link.appendChild(title);
    link.appendChild(excerpt);
    row.appendChild(link);
    container.appendChild(row);
  }
}

// Keyboard navigation for search results
// ArrowDown/Up to navigate, Enter to follow link, Escape calls onClose
export function setupKeyboardNav(
  input: HTMLInputElement,
  resultsContainer: HTMLElement,
  onClose?: () => void,
): void {
  let activeIndex = -1;

  function getResults(): HTMLElement[] {
    return Array.from(resultsContainer.querySelectorAll<HTMLElement>(".search-result"));
  }

  function setActive(results: HTMLElement[], index: number): void {
    results.forEach((r) => r.classList.remove("kb-active"));
    activeIndex = index;
    if (index >= 0 && index < results.length) {
      results[index].classList.add("kb-active");
      results[index].scrollIntoView({ block: "nearest" });
    }
  }

  // Reset active index when results change
  const observer = new MutationObserver(() => {
    activeIndex = -1;
  });
  observer.observe(resultsContainer, { childList: true });

  input.addEventListener("keydown", (e: KeyboardEvent) => {
    if (e.key === "Escape") {
      e.preventDefault();
      if (onClose) onClose();
      return;
    }

    const results = getResults();
    if (!results.length) return;

    if (e.key === "ArrowDown") {
      e.preventDefault();
      setActive(results, Math.min(activeIndex + 1, results.length - 1));
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setActive(results, Math.max(activeIndex - 1, 0));
    } else if (e.key === "Enter" && activeIndex >= 0) {
      e.preventDefault();
      const link = results[activeIndex].querySelector<HTMLAnchorElement>("a");
      if (link) link.click();
    }
  });
}

// Platform detection for keyboard shortcut display
export function isMac(): boolean {
  return /Mac|iPhone|iPad/.test(navigator.platform);
}

// Dev mode fallback placeholder
export function createDevFallback(container: HTMLElement): void {
  const wrapper = document.createElement("div");
  wrapper.className = "search-dev-fallback";

  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("width", "18");
  svg.setAttribute("height", "18");
  svg.setAttribute("viewBox", "0 0 24 24");
  svg.setAttribute("fill", "none");
  svg.setAttribute("stroke", "currentColor");
  svg.setAttribute("stroke-width", "2");
  const circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
  circle.setAttribute("cx", "11");
  circle.setAttribute("cy", "11");
  circle.setAttribute("r", "8");
  const line = document.createElementNS("http://www.w3.org/2000/svg", "line");
  line.setAttribute("x1", "21");
  line.setAttribute("y1", "21");
  line.setAttribute("x2", "16.65");
  line.setAttribute("y2", "16.65");
  svg.appendChild(circle);
  svg.appendChild(line);

  const span = document.createElement("span");
  span.textContent = "Search notes... (available in production build)";

  wrapper.appendChild(svg);
  wrapper.appendChild(span);
  container.appendChild(wrapper);
}
